import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
export class ApprovalStore{
 constructor(stateRoot,audit=null){fs.mkdirSync(stateRoot,{recursive:true});this.file=path.join(stateRoot,'approvals.json');this.audit=audit;if(!fs.existsSync(this.file))fs.writeFileSync(this.file,'[]\n');}
 _read(){try{return JSON.parse(fs.readFileSync(this.file,'utf8'));}catch{return [];}} _write(x){fs.writeFileSync(this.file,JSON.stringify(x,null,2)+'\n');}
 list({status=null,limit=100}={}){let x=this._read();if(status)x=x.filter(a=>a.status===status);return x.slice(-Math.max(1,Number(limit)||100)).reverse();}
 get(id){return this._read().find(x=>x.id===id)||null;}
 request({actionEnvelopeId=null,taskId=null,operation='',risk='high',reason='',expiresInMs=3600000}={}){const now=Date.now(),a={id:`approval-${crypto.randomUUID()}`,actionEnvelopeId,taskId,operation:String(operation),risk:String(risk),reason:String(reason),status:'PENDING',requestedAt:new Date(now).toISOString(),expiresAt:new Date(now+Math.max(60000,Number(expiresInMs)||3600000)).toISOString(),decidedAt:null,decision:null};const rows=this._read();rows.push(a);this._write(rows);this.audit?.append({type:'approval.request',approvalId:a.id,taskId,actionEnvelopeId,risk:a.risk});return a;}
 decide(id,decision){const d=String(decision||'').toUpperCase();if(!['APPROVE','DENY'].includes(d))return {state:'BLOCKED',message:'Decision must be APPROVE or DENY.'};const rows=this._read(),i=rows.findIndex(x=>x.id===id);if(i<0)return {state:'FAILURE',message:'Approval not found.'};const a=rows[i];if(a.status!=='PENDING')return {state:'BLOCKED',message:`Approval is already ${a.status}.`,approval:a};if(Date.now()>Date.parse(a.expiresAt)){rows[i]={...a,status:'EXPIRED',decidedAt:new Date().toISOString()};this._write(rows);return {state:'TIMEOUT',message:'Approval expired.',approval:rows[i]};}rows[i]={...a,status:d==='APPROVE'?'APPROVED':'DENIED',decision:d,decidedAt:new Date().toISOString()};this._write(rows);this.audit?.append({type:'approval.decision',approvalId:id,decision:d});return {state:d==='APPROVE'?'SUCCESS':'DENIED',message:`Approval ${rows[i].status.toLowerCase()}.`,approval:rows[i]};}
}
