import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
export class AutonomyStore{
 constructor(stateRoot,audit=null){fs.mkdirSync(stateRoot,{recursive:true});this.file=path.join(stateRoot,'autonomy-leases.json');this.audit=audit;if(!fs.existsSync(this.file))fs.writeFileSync(this.file,'[]\n');}
 _read(){try{return JSON.parse(fs.readFileSync(this.file,'utf8'));}catch{return [];}} _write(x){fs.writeFileSync(this.file,JSON.stringify(x,null,2)+'\n');}
 list(){return this._read().map(x=>this._normalize(x)).reverse();} get(id){const x=this._read().find(a=>a.id===id);return x?this._normalize(x):null;}
 _normalize(x){if(x.status==='ACTIVE'&&Date.now()>Date.parse(x.expiresAt))return {...x,status:'EXPIRED'};return x;}
 grant({subject='user:onechat',agent='task-engine',scope=[],riskCeiling='medium',maxActions=10,durationMs=3600000}={}){const now=Date.now();const lease={id:`lease-${crypto.randomUUID()}`,subject,agent,scope:[...new Set((scope||[]).map(String))],riskCeiling:String(riskCeiling),maxActions:Math.max(1,Number(maxActions)||10),usedActions:0,status:'ACTIVE',createdAt:new Date(now).toISOString(),expiresAt:new Date(now+Math.max(60000,Number(durationMs)||3600000)).toISOString()};const rows=this._read();rows.push(lease);this._write(rows);this.audit?.append({type:'autonomy.grant',leaseId:lease.id,scope:lease.scope,riskCeiling:lease.riskCeiling,maxActions:lease.maxActions});return {state:'SUCCESS',message:'Bounded autonomy lease granted.',lease};}
 revoke(id){const rows=this._read(),i=rows.findIndex(x=>x.id===id);if(i<0)return {state:'FAILURE',message:'Autonomy lease not found.'};rows[i]={...rows[i],status:'REVOKED',revokedAt:new Date().toISOString()};this._write(rows);this.audit?.append({type:'autonomy.revoke',leaseId:id});return {state:'SUCCESS',message:'Autonomy lease revoked.',lease:rows[i]};}
 authorize(id,{operation='',risk='low'}={}){const rows=this._read(),i=rows.findIndex(x=>x.id===id);if(i<0)return {state:'DENIED',message:'Autonomy lease not found.'};let a=this._normalize(rows[i]);if(a.status!=='ACTIVE')return {state:'DENIED',message:`Autonomy lease is ${a.status}.`,lease:a};if(a.usedActions>=a.maxActions)return {state:'DENIED',message:'Autonomy action limit exhausted.',lease:a};if(a.scope.length&&!a.scope.includes(operation))return {state:'DENIED',message:'Operation is outside autonomy scope.',lease:a};const rank={low:0,medium:1,high:2,critical:3};if((rank[String(risk)]??3)>(rank[a.riskCeiling]??1))return {state:'DENIED',message:'Operation exceeds autonomy risk ceiling.',lease:a};rows[i]={...rows[i],usedActions:rows[i].usedActions+1};this._write(rows);return {state:'SUCCESS',message:'Autonomy lease authorizes this bounded operation.',lease:rows[i]};}
}
