import {spawn} from "node:child_process";
import fs from "node:fs";import path from "node:path";import {fileURLToPath} from "node:url";
const ROOT=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
function py(script,args=[],timeout=240000){return new Promise(resolve=>{const p=spawn(process.env.PYTHON||"python3",[path.join(ROOT,script),...args],{cwd:ROOT});let out="",err="";let settled=false;const done=x=>{if(settled)return;settled=true;clearTimeout(timer);resolve(x)};const timer=setTimeout(()=>{p.kill("SIGKILL");done({state:"TIMEOUT",message:`${script} timed out.`})},timeout);p.stdout.on("data",d=>out+=d);p.stderr.on("data",d=>err+=d);p.on("error",e=>done({state:"UNAVAILABLE",message:e.message}));p.on("close",code=>{if(settled)return;const line=out.trim().split(/\n/).filter(Boolean).at(-1)||"";try{const x=JSON.parse(line);done({...x,exitCode:code})}catch{done({state:code===0?"SUCCESS":"ERROR",message:(err||out||`${script} exited ${code}`).slice(0,4000),exitCode:code})}})})}
export class ModelLab{
 constructor({learning,audit,stateRoot}){this.learning=learning;this.audit=audit;this.stateFile=path.join(stateRoot,"model-runs.json");if(!fs.existsSync(this.stateFile))fs.writeFileSync(this.stateFile,"[]");}
 presets(){try{return JSON.parse(fs.readFileSync(path.join(ROOT,"model","config_presets.json"),"utf8"))}catch(e){return {format:"unavailable",presets:{},error:e.message}}}
 runs(){try{return JSON.parse(fs.readFileSync(this.stateFile,"utf8"))}catch{return []}}
 remember(run){const all=this.runs();all.push({recordedAt:new Date().toISOString(),...run});fs.writeFileSync(this.stateFile,JSON.stringify(all.slice(-100),null,2));}
 async prepareDataset(){const learned=this.learning.build();if(learned.state!=="SUCCESS")return learned;const language=await py("storage/export_training.py",["--definitions",process.env.FORGELM_MAX_DEFINITIONS||"5000","--dialogues",process.env.FORGELM_MAX_DIALOGUES||"5000"],60000);const built=await py("model/data_pipeline.py",["--extra","model/data/seed.txt","--web-corpus","model/data/web-corpus.jsonl","--max-web-records",process.env.FORGELM_MAX_WEB_RECORDS||"5000","--language-database","model/data/language-database.jsonl"],60000);if(built.state==="SUCCESS")await py("model/build_corpus.py",[],60000);this.audit?.append({type:"model.dataset.build",state:built.state,accepted:built.counts?.accepted||0});return {...built,learningExport:learned,languageDatabase:language};}
 async train({steps=40,preset="termux-tiny",gradAccum=1}={}){const prep=await this.prepareDataset();if(prep.state!=="SUCCESS")return {state:"FAILURE",message:"Dataset preparation failed; training was not started.",dataset:prep};const r=await py("model/cli.py",["train","--steps",String(steps),"--preset",preset,"--grad-accum",String(gradAccum)],300000);if(r.state==="SUCCESS")this.remember(r);this.audit?.append({type:"model.train",state:r.state,preset,steps});return {...r,dataset:{counts:prep.counts,integrity:prep.integrity}};}
 trainTokenizer(vocabSize=512){return py("model/tokenizer.py",["train","--corpus","model/data/training-corpus.txt","--vocab-size",String(vocabSize)],120000)}
 benchmark(){return py("model/benchmark_inference.py",[],60000)}
 analyzeSources(){return py("research/analyze_sources.py",[],60000)}
 hardware(){return py("model/hardware_profile.py",[],20000)}
 status(){const ps=this.presets();const tok=fs.existsSync(path.join(ROOT,"model","tokenizers","forgelm.pyngram.json"))?"python-byte-ngram":(fs.existsSync(path.join(ROOT,"model","tokenizers","forgelm.model"))?"sentencepiece-or-byte-fallback":"byte-action");return {state:"SUCCESS",presets:Object.keys(ps.presets||{}),presetDetails:ps.presets||{},tokenizer:tok,runs:this.runs().slice(-10),truth:ps.truth||null};}
}
